spring:
  application:
    name: "Order"
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  security:
    token:
      secret: "12345678"